minst1:
  split: "train"
  eval_split: "test"
  env_device: "cpu"
  learning_rate: 0.0003
  entropy_coef: 0.01
  baseline_tau: 0.05
  eval_interval_episodes: 1000
  target_accuracy: 0.99
  patience: 3
  max_wall_seconds: None
  seed: 42
  render_eval: false
