config:
  env: 'darkroom_heldout'
  envs: 100000
  envs_eval: 100
  hists: 1
  samples: 1
  H: 100
  dim: 10
  lin_d: 2
  var: 0.0
  cov: 0.0
  env_id_start: -1
  env_id_end: -1
  embd: 32
  head: 1
  layer: 3
  lr: 0.001
  dropout: 0
  shuffle: False
  num_epochs: 1000
  epoch: -1
  test_cov: -1.0
  horizon: -1
  n_eval: 100
  seed: 0